// Code generated by protoc-gen-go. DO NOT EDIT.
// source: animeengineservice.proto

package v1beta1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetReviewsRequest struct {
	Limit                *int32   `protobuf:"varint,1,req,name=limit" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReviewsRequest) Reset()         { *m = GetReviewsRequest{} }
func (m *GetReviewsRequest) String() string { return proto.CompactTextString(m) }
func (*GetReviewsRequest) ProtoMessage()    {}
func (*GetReviewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e3d51045e98abed, []int{0}
}

func (m *GetReviewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewsRequest.Unmarshal(m, b)
}
func (m *GetReviewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewsRequest.Marshal(b, m, deterministic)
}
func (m *GetReviewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewsRequest.Merge(m, src)
}
func (m *GetReviewsRequest) XXX_Size() int {
	return xxx_messageInfo_GetReviewsRequest.Size(m)
}
func (m *GetReviewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewsRequest proto.InternalMessageInfo

func (m *GetReviewsRequest) GetLimit() int32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

type GetReviewsResponse struct {
	Results              []*GetReviewsResponse_Review `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetReviewsResponse) Reset()         { *m = GetReviewsResponse{} }
func (m *GetReviewsResponse) String() string { return proto.CompactTextString(m) }
func (*GetReviewsResponse) ProtoMessage()    {}
func (*GetReviewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e3d51045e98abed, []int{1}
}

func (m *GetReviewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewsResponse.Unmarshal(m, b)
}
func (m *GetReviewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewsResponse.Marshal(b, m, deterministic)
}
func (m *GetReviewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewsResponse.Merge(m, src)
}
func (m *GetReviewsResponse) XXX_Size() int {
	return xxx_messageInfo_GetReviewsResponse.Size(m)
}
func (m *GetReviewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewsResponse proto.InternalMessageInfo

func (m *GetReviewsResponse) GetResults() []*GetReviewsResponse_Review {
	if m != nil {
		return m.Results
	}
	return nil
}

type GetReviewsResponse_Review struct {
	Score *int32 `protobuf:"varint,1,req,name=score" json:"score,omitempty"`
	//Anilist User Id
	Uid *int32 `protobuf:"varint,2,req,name=uid" json:"uid,omitempty"`
	//Anilist Media Id
	Mid                  *int32   `protobuf:"varint,3,req,name=mid" json:"mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReviewsResponse_Review) Reset()         { *m = GetReviewsResponse_Review{} }
func (m *GetReviewsResponse_Review) String() string { return proto.CompactTextString(m) }
func (*GetReviewsResponse_Review) ProtoMessage()    {}
func (*GetReviewsResponse_Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e3d51045e98abed, []int{1, 0}
}

func (m *GetReviewsResponse_Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewsResponse_Review.Unmarshal(m, b)
}
func (m *GetReviewsResponse_Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewsResponse_Review.Marshal(b, m, deterministic)
}
func (m *GetReviewsResponse_Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewsResponse_Review.Merge(m, src)
}
func (m *GetReviewsResponse_Review) XXX_Size() int {
	return xxx_messageInfo_GetReviewsResponse_Review.Size(m)
}
func (m *GetReviewsResponse_Review) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewsResponse_Review.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewsResponse_Review proto.InternalMessageInfo

func (m *GetReviewsResponse_Review) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *GetReviewsResponse_Review) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *GetReviewsResponse_Review) GetMid() int32 {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return 0
}

func init() {
	proto.RegisterType((*GetReviewsRequest)(nil), "GetReviewsRequest")
	proto.RegisterType((*GetReviewsResponse)(nil), "GetReviewsResponse")
	proto.RegisterType((*GetReviewsResponse_Review)(nil), "GetReviewsResponse.Review")
}

func init() { proto.RegisterFile("animeengineservice.proto", fileDescriptor_9e3d51045e98abed) }

var fileDescriptor_9e3d51045e98abed = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x6a, 0x84, 0x30,
	0x10, 0x86, 0xab, 0x62, 0x0b, 0xd3, 0x4b, 0x9b, 0xf6, 0x10, 0x3c, 0x89, 0x27, 0x7b, 0xc9, 0x41,
	0x0a, 0xbd, 0xb6, 0xbd, 0xf4, 0x9e, 0x37, 0x28, 0x3a, 0x2c, 0x03, 0x26, 0x71, 0x33, 0xd1, 0x7d,
	0x8b, 0x7d, 0xe6, 0x25, 0x06, 0xd9, 0x05, 0xf7, 0x36, 0xff, 0xc7, 0x0f, 0xdf, 0xfc, 0x20, 0xff,
	0x2d, 0x19, 0x44, 0x7b, 0x20, 0x8b, 0x8c, 0x7e, 0xa1, 0x1e, 0xd5, 0xe4, 0x5d, 0x70, 0xcd, 0x07,
	0xbc, 0xfe, 0x61, 0xd0, 0xb8, 0x10, 0x9e, 0x58, 0xe3, 0x71, 0x46, 0x0e, 0xe2, 0x1d, 0xca, 0x91,
	0x0c, 0x05, 0x99, 0xd5, 0x79, 0x5b, 0xea, 0x14, 0x9a, 0x73, 0x06, 0xe2, 0xb6, 0xcb, 0x93, 0xb3,
	0x8c, 0xe2, 0x13, 0x9e, 0x3c, 0xf2, 0x3c, 0x06, 0x96, 0x59, 0x5d, 0xb4, 0xcf, 0x5d, 0xa5, 0xf6,
	0x2d, 0x95, 0xb2, 0xde, 0xaa, 0xd5, 0x2f, 0x3c, 0x26, 0x14, 0x65, 0xdc, 0x3b, 0x8f, 0x9b, 0x6c,
	0x0d, 0xe2, 0x05, 0x8a, 0x99, 0x06, 0x99, 0xaf, 0x2c, 0x9e, 0x91, 0x18, 0x1a, 0x64, 0x91, 0x88,
	0xa1, 0xa1, 0xfb, 0x86, 0xf2, 0x27, 0xee, 0x12, 0x5f, 0x00, 0x57, 0xa5, 0x10, 0x6a, 0xb7, 0xa8,
	0x7a, 0xbb, 0xf3, 0x53, 0xf3, 0x70, 0x09, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x70, 0xbc, 0x07, 0x18,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AnimeClient is the client API for Anime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnimeClient interface {
	GetReviews(ctx context.Context, in *GetReviewsRequest, opts ...grpc.CallOption) (*GetReviewsResponse, error)
}

type animeClient struct {
	cc grpc.ClientConnInterface
}

func NewAnimeClient(cc grpc.ClientConnInterface) AnimeClient {
	return &animeClient{cc}
}

func (c *animeClient) GetReviews(ctx context.Context, in *GetReviewsRequest, opts ...grpc.CallOption) (*GetReviewsResponse, error) {
	out := new(GetReviewsResponse)
	err := c.cc.Invoke(ctx, "/Anime/GetReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnimeServer is the server API for Anime service.
type AnimeServer interface {
	GetReviews(context.Context, *GetReviewsRequest) (*GetReviewsResponse, error)
}

// UnimplementedAnimeServer can be embedded to have forward compatible implementations.
type UnimplementedAnimeServer struct {
}

func (*UnimplementedAnimeServer) GetReviews(ctx context.Context, req *GetReviewsRequest) (*GetReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReviews not implemented")
}

func RegisterAnimeServer(s *grpc.Server, srv AnimeServer) {
	s.RegisterService(&_Anime_serviceDesc, srv)
}

func _Anime_GetReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeServer).GetReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Anime/GetReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeServer).GetReviews(ctx, req.(*GetReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Anime_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Anime",
	HandlerType: (*AnimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReviews",
			Handler:    _Anime_GetReviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "animeengineservice.proto",
}
